import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/admin/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'users',
        path: '/admin/users',
        title: 'Users',
        translateKey: 'nav.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'category',
        path: '/admin/category',
        title: 'Category',
        translateKey: 'nav.category',
        icon: 'category',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'subcategory',
        path: '/admin/subcategory',
        title: 'Sub Category',
        translateKey: 'nav.subcategory',
        icon: 'category',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'theme',
        path: '/admin/theme',
        title: 'Themes',
        translateKey: 'nav.theme',
        icon: 'theme',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'music',
        path: '/admin/music',
        title: 'Musics',
        translateKey: 'nav.music',
        icon: 'music',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'setting',
        path: '/admin/setting',
        title: 'Setting',
        translateKey: 'nav.setting',
        icon: 'setting',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'notificationsend',
        path: '/admin/notificationsend',
        title: 'Notification',
        translateKey: 'nav.notificationsend',
        icon: 'notificationsend',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'about',
        path: '/admin/about',
        title: 'About Us',
        translateKey: 'nav.about',
        icon: 'about',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'subscribers',
        path: '/admin/subscribers',
        title: 'Subscribers',
        translateKey: 'nav.subscribers',
        icon: 'premium',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
];

export default navigationConfig
